# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# TODO: implement multi OS for linux and mac https://docs.travis-ci.com/user/multi-os/

language: r
r: release
cache: packages
r_packages: rgdal # Might be missing, or test doesn't load

dist: xenial
addons:
  apt:
    #sources:
    #  - ppa:ubuntugis/ubuntugis-unstable
    # Need to add key and more details if using unstable, stable is already included
    packages:
      - libproj-dev 
      - libgeos-dev
      - libgdal-dev
