# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# TODO: implement multi OS for linux and mac https://docs.travis-ci.com/user/multi-os/

language: r
r: release
sudo: false
cache: packages

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
#  - tlmgr install hanging