# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# TODO: implement multi OS for linux and mac https://docs.travis-ci.com/user/multi-os/

language: r
r: release
cache: packages
r_packages: rgdal #Even though dep=TRUE seems to miss rgdal from raster optional

dist: xenial
addons:
  apt:
    sources:
      - ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libproj-dev 
      - libgeos-dev
      - libgdal-dev
