# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# TODO: implement multi OS for linux and mac https://docs.travis-ci.com/user/multi-os/

language: r
r: release
#cache: packages
sudo: required
dist: bionic

warnings_are_errors: false

# Skip tests
# r_check_args: '--no-tests --no-examples'

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev 
      - libgeos-dev
      - libgdal-dev


