# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# TODO: implement multi OS for linux and mac https://docs.travis-ci.com/user/multi-os/

language: r
r: release
cache: packages

dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev 
      - libgeos-dev
      - libgdal-dev
      - gdal-bin # shouldn't be needed, but rgdal is being a problem

# Tests are failing to load rgdal
r_packages: 
  #- rgdal
  - covr

# Lets try getting it from ubuntu repos
r_binary_packages:
  - rgdal
  

after_success:
- Rscript -e 'library(covr); codecov()'